name: Build-Lean-lede
on:
  push:
    branches:
      - master
    paths:
      - '.github/workflows/Build-Lean-lede.yml'
      -  'lean-lede/x86_64/.config'
      -  'lean-lede/rpi4/.config'
      -  'lean-lede/rpi/.config'
      -  'lean-lede/rpi32/.config'
      -  'lean-lede/mt7621/.config'
  schedule:
        - cron: 0 */4 * * *

jobs:
  x86:
    runs-on: ubuntu-latest
    steps:    
    - name: Prepare environment.
      env:
          DEBIAN_FRONTEND: noninteractive
      run: |
        bash <(curl -fsSL https://raw.githubusercontent.com/1orz/My-action/master/lean-lede/prenv.sh)
        
    - name: Clone Source
      run: |
        git clone https://github.com/coolsnowwolf/lede
        
    - name: Download and Load custom configuration
      run: |
        cd lede
        curl -fsSL https://raw.githubusercontent.com/1orz/My-action/master/lean-lede/x86_64/.config >.config
        bash <(curl -fsSL https://raw.githubusercontent.com/1orz/My-action/master/lean-lede/diy.sh)
        make defconfig
        
    - name: Download package
      run: |
        cd lede
        make download -j8
        find dl -size -1024c -exec ls -l {} \;
        find dl -size -1024c -exec rm -f {} \;
        sudo df -h
        
    - name: Multi-core or Single core compile
      run: |
        cd lede
        echo -e "$(nproc) thread compile"
        sudo df -h
        make -j$(nproc) || make -j1 V=s
        sudo df -h
        
    - name: Upload entire bin directory
      uses: actions/upload-artifact@master
      if: always()
      with:
        name: LEDE-x86_64-bin-dictionary
        path: lede/bin
        
    - name: Only Upload Packages to Download Station
      if: success()
      run: |
        cd lede/bin
        zip -r -o -q x86_64-Package.zip . -i *.ipk
        curl -F "token=${{ secrets.UPLOAD_TOKEN }}" -F "location=Router/LEDE/x86_64/Lean-Package" -F "file=@x86_64-Package.zip" ${{ secrets.MAIN_UPLOAD_PROCESSOR }}
        #curl --socks5 ${{ secrets.PROXY_ADDR }} -U ${{ secrets.PROXY_USER }} -F "token=${{ secrets.UPLOAD_TOKEN }}" -F "location=Router/LEDE/x86_64/Lean-Package" -F "file=@x86_64-Package.zip" ${{ secrets.CN_STATION_PROCESSOR }}
        
    - name: Setup Upload dictionary
      if: always()
      run: |
        cd lede/bin/targets/*/*
        rm -rf packages
        echo "::set-env name=FIRMWARE::$(pwd)"
        
    - name: Only Upload firmware (Without packages)
      uses: actions/upload-artifact@master
      if: always()
      with:
        name: x86_64
        path: ${{ env.FIRMWARE }}
        
    - name: Upload firmware to Download Station (Without packages)
      if: success()
      run: |
        cd lede/bin/targets/*/*
        zip -r -o -q x86_64.zip . -i *.gz
        curl -F "token=${{ secrets.UPLOAD_TOKEN }}" -F "location=Router/LEDE/x86_64/Lean" -F "file=@x86_64.zip" ${{ secrets.MAIN_UPLOAD_PROCESSOR }}
        #curl --socks5 ${{ secrets.PROXY_ADDR }} -U ${{ secrets.PROXY_USER }} -F "token=${{ secrets.UPLOAD_TOKEN }}" -F "location=Router/LEDE/x86_64/Lean" -F "file=@x86_64.zip" ${{ secrets.CN_STATION_PROCESSOR }}

  Raspberry3:
    runs-on: ubuntu-latest
    steps:
    - name: Prepare environment.
      env:
          DEBIAN_FRONTEND: noninteractive
      run: |
        bash <(curl -fsSL https://raw.githubusercontent.com/1orz/My-action/master/lean-lede/prenv.sh)
        
    - name: Clone Source
      run: |
        git clone https://github.com/coolsnowwolf/lede
        
    - name: Download and Load custom configuration
      run: |
        cd lede
        curl -fsSL https://raw.githubusercontent.com/1orz/My-action/master/lean-lede/rpi/.config >.config
        bash <(curl -fsSL https://raw.githubusercontent.com/1orz/My-action/master/lean-lede/diy.sh)
        make defconfig
        
    - name: Download package
      run: |
        cd lede
        make download -j8
        find dl -size -1024c -exec ls -l {} \;
        find dl -size -1024c -exec rm -f {} \;
        
    - name: Multi-core or Single core compile
      run: |
        cd lede
        echo -e "$(nproc) thread compile"
        sudo df -h
        make -j$(nproc) || make -j1 V=s
        sudo df -h
        make -j1 V=s
        sudo df -h
        
    - name: Upload entire bin directory
      uses: actions/upload-artifact@master
      if: always()
      with:
        name: LEDE-RaspberryPi-bin-dictionary
        path: lede/bin
        
    - name: Only Upload Packages to Download Station
      if: success()
      run: |
        cd lede/bin
        zip -r -o -q rpi3-Package.zip . -i *.ipk
        curl -F "token=${{ secrets.UPLOAD_TOKEN }}" -F "location=Router/LEDE/RaspberryPi3/Lean-Package" -F "file=@rpi3-Package.zip" ${{ secrets.MAIN_UPLOAD_PROCESSOR }}
        #curl --socks5 ${{ secrets.PROXY_ADDR }} -U ${{ secrets.PROXY_USER }} -F "token=${{ secrets.UPLOAD_TOKEN }}" -F "location=Router/LEDE/RaspberryPi3/Lean-Package" -F "file=@rpi3-Package.zip" ${{ secrets.CN_STATION_PROCESSOR }}
        
    - name: Setup Upload dictionary
      if: always()
      run: |
        cd lede/bin
        rm -rf packages
        echo "::set-env name=FIRMWARE::$(pwd)"
        
    - name: Only Upload firmware (Without packages)
      uses: actions/upload-artifact@master
      if: always()
      with:
        name: RaspberryPi3b
        path: ${{ env.FIRMWARE }}
        
    - name: Upload firmware to Download Station (Without packages)
      if: success()
      run: |
        cd lede/bin/targets/*/*
        zip -r -o -q rpi3.zip . -i *.gz
        curl -F "token=${{ secrets.UPLOAD_TOKEN }}" -F "location=Router/LEDE/RaspberryPi3/Lean" -F "file=@rpi3.zip" ${{ secrets.MAIN_UPLOAD_PROCESSOR }}
        #curl --socks5 ${{ secrets.PROXY_ADDR }} -U ${{ secrets.PROXY_USER }} -F "token=${{ secrets.UPLOAD_TOKEN }}" -F "location=Router/LEDE/RaspberryPi3/Lean" -F "file=@rpi3.zip" ${{ secrets.CN_STATION_PROCESSOR }}

  Raspberry32bit:
    runs-on: ubuntu-latest
    steps:
    - name: Prepare environment.
      env:
          DEBIAN_FRONTEND: noninteractive
      run: |
        bash <(curl -fsSL https://raw.githubusercontent.com/1orz/My-action/master/lean-lede/prenv.sh)
        
    - name: Clone Source
      run: |
        git clone https://github.com/coolsnowwolf/lede
        
    - name: Download and Load custom configuration
      run: |
        cd lede
        curl -fsSL https://raw.githubusercontent.com/1orz/My-action/master/lean-lede/rpi32/.config >.config
        bash <(curl -fsSL https://raw.githubusercontent.com/1orz/My-action/master/lean-lede/diy.sh)
        make defconfig
        
    - name: Download package
      run: |
        cd lede
        make download -j8
        find dl -size -1024c -exec ls -l {} \;
        find dl -size -1024c -exec rm -f {} \;
        
    - name: Multi-core or Single core compile
      run: |
        cd lede
        echo -e "$(nproc) thread compile"
        sudo df -h
        make -j$(nproc) || make -j1 V=s
        sudo df -h
        
    - name: Upload entire bin directory
      uses: actions/upload-artifact@master
      if: always()
      with:
        name: LEDE-RaspberryPi-32bit-bin-dictionary
        path: lede/bin
        
    - name: Only Upload Packages to Download Station
      if: success()
      run: |
        cd lede/bin
        zip -r -o -q rpi-32bit-Package.zip . -i *.ipk
        curl -F "token=${{ secrets.UPLOAD_TOKEN }}" -F "location=Router/LEDE/RaspberryPi-32bit/Lean-Package" -F "file=@rpi-32bit-Package.zip" ${{ secrets.MAIN_UPLOAD_PROCESSOR }}
        #curl --socks5 ${{ secrets.PROXY_ADDR }} -U ${{ secrets.PROXY_USER }} -F "token=${{ secrets.UPLOAD_TOKEN }}" -F "location=Router/LEDE/RaspberryPi-32bit/Lean-Package" -F "file=@rpi-32bit-Package.zip" ${{ secrets.CN_STATION_PROCESSOR }}
        
    - name: Setup Upload dictionary
      if: always()
      run: |
        cd lede/bin
        rm -rf packages
        echo "::set-env name=FIRMWARE::$(pwd)"
        
    - name: Only Upload firmware (Without packages)
      uses: actions/upload-artifact@master
      if: always()
      with:
        name: RaspberryPi-32bit
        path: ${{ env.FIRMWARE }}
        
    - name: Upload firmware to Download Station (Without packages)
      if: success()
      run: |
        cd lede/bin/targets/*/*
        zip -r -o -q rpi-32bit.zip . -i *.gz
        curl -F "token=${{ secrets.UPLOAD_TOKEN }}" -F "location=Router/LEDE/RaspberryPi-32bit/Lean" -F "file=@rpi-32bit.zip" ${{ secrets.MAIN_UPLOAD_PROCESSOR }}
        #curl --socks5 ${{ secrets.PROXY_ADDR }} -U ${{ secrets.PROXY_USER }} -F "token=${{ secrets.UPLOAD_TOKEN }}" -F "location=Router/LEDE/RaspberryPi-32bit/Lean" -F "file=@rpi-32bit.zip" ${{ secrets.CN_STATION_PROCESSOR }}
        
  RaspberryPi4:
    runs-on: ubuntu-latest
    steps:
    - name: Prepare environment.
      env:
          DEBIAN_FRONTEND: noninteractive
      run: |
        bash <(curl -fsSL https://raw.githubusercontent.com/1orz/My-action/master/lean-lede/prenv.sh)
        
    - name: Clone Source
      run: |
        git clone https://github.com/coolsnowwolf/lede
        
    - name: Download and Load custom configuration
      run: |
        cd lede
        curl -fsSL https://raw.githubusercontent.com/1orz/My-action/master/lean-lede/rpi4/.config >.config
        bash <(curl -fsSL https://raw.githubusercontent.com/1orz/My-action/master/lean-lede/diy.sh)
        make defconfig
        
    - name: Download package
      run: |
        cd lede
        make download -j8
        find dl -size -1024c -exec ls -l {} \;
        find dl -size -1024c -exec rm -f {} \;
        
    - name: Multi-core or Single core compile
      run: |
        cd lede
        echo -e "$(nproc) thread compile"
        sudo df -h
        make -j$(nproc) || make -j1 V=s
        sudo df -h
        
    - name: Only Upload Packages to Download Station
      if: success()
      run: |
        cd lede/bin
        zip -r -o -q rpi4-Package.zip . -i *.ipk
        curl -F "token=${{ secrets.UPLOAD_TOKEN }}" -F "location=Router/LEDE/RaspberryPi4/Lean-Package" -F "file=@rpi4-Package.zip" ${{ secrets.MAIN_UPLOAD_PROCESSOR }}
        #curl --socks5 ${{ secrets.PROXY_ADDR }} -U ${{ secrets.PROXY_USER }} -F "token=${{ secrets.UPLOAD_TOKEN }}" -F "location=Router/LEDE/RaspberryPi4/Lean-Package" -F "file=@rpi4-Package.zip" ${{ secrets.CN_STATION_PROCESSOR }}

        
    - name: Setup Upload dictionary
      if: always()
      run: |
        cd lede/bin
        rm -rf packages
        echo "::set-env name=FIRMWARE::$(pwd)"
        
    - name: Only Upload firmware (Without packages)
      uses: actions/upload-artifact@master
      if: always()
      with:
        name: RaspberryPi4
        path: ${{ env.FIRMWARE }}
        
    - name: Upload firmware to Download Station (Without packages)
      if: success()
      run: |
        cd lede/bin/targets/*/*
        zip -r -o -q rpi4.zip . -i *.gz
        curl -F "token=${{ secrets.UPLOAD_TOKEN }}" -F "location=Router/LEDE/RaspberryPi4/Lean" -F "file=@rpi4.zip" ${{ secrets.MAIN_UPLOAD_PROCESSOR }}
        #curl --socks5 ${{ secrets.PROXY_ADDR }} -U ${{ secrets.PROXY_USER }} -F "token=${{ secrets.UPLOAD_TOKEN }}" -F "location=Router/LEDE/RaspberryPi4/Lean" -F "file=@rpi4.zip" ${{ secrets.CN_STATION_PROCESSOR }}
  MT7621:
    runs-on: ubuntu-latest
    steps:
    - name: Prepare environment.
      env:
          DEBIAN_FRONTEND: noninteractive
      run: |
        bash <(curl -fsSL https://raw.githubusercontent.com/1orz/My-action/master/lean-lede/prenv.sh)
        
    - name: Clone Source
      run: |
        git clone https://github.com/coolsnowwolf/lede
        
    - name: Download and Load custom configuration
      run: |
        cd lede
        curl -fsSL https://raw.githubusercontent.com/1orz/My-action/master/lean-lede/mt7621/.config >.config
        bash <(curl -fsSL https://raw.githubusercontent.com/1orz/My-action/master/lean-lede/diy.sh)
        make defconfig
        
    - name: Download package
      run: |
        cd lede
        make download -j8
        find dl -size -1024c -exec ls -l {} \;
        find dl -size -1024c -exec rm -f {} \;
        
    - name: Multi-core or Single core compile
      run: |
        cd lede
        echo -e "$(nproc) thread compile"
        sudo df -h
        make -j$(nproc) || make -j1 V=s
        sudo df -h
        
    - name: Only Upload Packages to Download Station
      if: success()
      run: |
        cd lede/bin
        zip -r -o -q  mt7621-Package.zip . -i *.ipk
        curl -F "token=${{ secrets.UPLOAD_TOKEN }}" -F "location=Router/LEDE/XiaoMi/XiaoMi-AC2100/Lean-Package" -F "file=@mt7621-Package.zip" ${{ secrets.MAIN_UPLOAD_PROCESSOR }}
        #curl --socks5 ${{ secrets.PROXY_ADDR }} -U ${{ secrets.PROXY_USER }} -F "token=${{ secrets.UPLOAD_TOKEN }}" -F "location=Router/LEDE/XiaoMi/XiaoMi-AC2100/Lean-Package" -F "file=@mt7621-Package.zip" ${{ secrets.CN_STATION_PROCESSOR }}

    - name: Setup Upload dictionary
      if: always()
      run: |
        cd lede/bin
        rm -rf packages
        echo "::set-env name=FIRMWARE::$(pwd)"
        
    - name: Only Upload firmware (Without packages)
      uses: actions/upload-artifact@master
      if: always()
      with:
        name: mt7621
        path: ${{ env.FIRMWARE }}
        
    - name: Upload firmware to Download Station (Without packages)
      if: success()
      run: |
        cd lede/bin/targets/*/*
        zip -r -o -q mt7621.zip . -i *.bin
        curl -F "token=${{ secrets.UPLOAD_TOKEN }}" -F "location=Router/LEDE/XiaoMi/XiaoMi-AC2100/Lean" -F "file=@mt7621.zip" ${{ secrets.MAIN_UPLOAD_PROCESSOR }}
        #curl --socks5 ${{ secrets.PROXY_ADDR }} -U ${{ secrets.PROXY_USER }} -F "token=${{ secrets.UPLOAD_TOKEN }}" -F "location=Router/LEDE/XiaoMi/XiaoMi-AC2100/Lean" -F "file=@mt7621.zip" ${{ secrets.CN_STATION_PROCESSOR }}
